# fred_requirements.yaml
# FRED Economic Data Collection Configuration
# Federal Reserve Economic Data API - Enhanced Coverage

fred:
  indicators:
    # 🇦🇺 AUSTRALIAN ECONOMIC INDICATORS (Primary Focus)
    
    # Inflation & Prices
    - indicator: CPALTT01AUQ657N
      name: "Australia Consumer Price Index"
      description: "CPI Total, All Items for Australia"
      category: "inflation"
      frequency: "quarterly"
      priority: "high"
      
    - indicator: CORESTICKM159SFRBATL
      name: "Australia Core CPI"  
      description: "Core Consumer Price Index for Australia"
      category: "inflation"
      frequency: "monthly"
      priority: "high"
      
    # Labour Market
    - indicator: LRHUTTTTAUM156S
      name: "Australia Unemployment Rate"
      description: "Unemployment Rate for Australia"
      category: "labour"
      frequency: "monthly"
      priority: "high"
      
    - indicator: LRHU24TTAUM156S  
      name: "Australia Youth Unemployment Rate"
      description: "Unemployment Rate: Aged 15-24 for Australia"
      category: "labour"
      frequency: "monthly"
      priority: "medium"
      
    # Interest Rates & Monetary Policy
    - indicator: IR3TIB01AUM156N
      name: "Australia 3-Month Interest Rate"
      description: "3 Month Interbank Rates for Australia"
      category: "monetary"
      frequency: "monthly"
      priority: "high"
      
    - indicator: IRLTLT01AUM156N
      name: "Australia 10-Year Government Bond Rate"
      description: "Interest Rates: Long-Term Government Bond Yields: 10-Year for Australia"
      category: "monetary"
      frequency: "monthly"
      priority: "high"
      
    # Economic Growth & Production
    - indicator: NGDPRSAXDCAUQ
      name: "Australia Real GDP"
      description: "Real Gross Domestic Product for Australia"
      category: "growth"
      frequency: "quarterly"
      priority: "high"
      
    - indicator: NYGDPPCAPKDAUS
      name: "Australia Real GDP per Capita"
      description: "Constant GDP per capita for Australia"
      category: "growth"
      frequency: "annual"
      priority: "medium"
      
    # Trade & External Sector
    - indicator: AUSBCABP6USD
      name: "Australia Current Account Balance"
      description: "Balance of Payments: Total Net Current Account for Australia"
      category: "trade"
      frequency: "annual"
      priority: "medium"
      
    - indicator: XTEXVA01AUA664N
      name: "Australia Exports"
      description: "International Merchandise Trade Statistics: Exports: Commodities for Australia"
      category: "trade"
      frequency: "annual"
      priority: "medium"
      
    # 🇺🇸 US ECONOMIC INDICATORS (Context & Comparison)
    
    # US Inflation & Federal Reserve
    - indicator: CPIAUCSL
      name: "US Consumer Price Index"
      description: "Consumer Price Index for All Urban Consumers"
      category: "us_inflation"
      frequency: "monthly"
      priority: "high"
      
    - indicator: FEDFUNDS
      name: "US Federal Funds Rate"
      description: "Federal Funds Effective Rate"
      category: "us_monetary"
      frequency: "monthly"
      priority: "high"
      
    # US Labour Market
    - indicator: UNRATE
      name: "US Unemployment Rate"
      description: "Unemployment Rate"
      category: "us_labour"
      frequency: "monthly"
      priority: "high"
      
    # US Economic Growth
    - indicator: GDP
      name: "US Gross Domestic Product"
      description: "Gross Domestic Product"
      category: "us_growth"
      frequency: "quarterly"
      priority: "medium"
      
    # 🌏 GLOBAL INDICATORS (International Context)
    
    - indicator: DEXUSAL
      name: "US Dollar / Australian Dollar Exchange Rate"
      description: "USD/AUD Exchange Rate"
      category: "fx"
      frequency: "daily"
      priority: "medium"
      
    # 🇨🇳 CHINESE ECONOMIC INDICATORS (Trading Partner Context)
    
    - indicator: INTDSRCNM193N
      name: "China Interest Rate" 
      description: "Interest Rates, Discount Rate for China"
      category: "cn_monetary"
      frequency: "monthly"
      priority: "medium"
      
    - indicator: CHNCPIALLMINMEI
      name: "China Consumer Price Index"
      description: "Consumer Price Index: Total for China" 
      category: "cn_inflation"
      frequency: "monthly"
      priority: "medium"
      
    - indicator: MKTGDPCNA646NWDB
      name: "China Gross Domestic Product"
      description: "Gross Domestic Product for China"
      category: "cn_growth"
      frequency: "annual"
      priority: "medium"
      
    - indicator: NYGDPPCAPKDCHN
      name: "China GDP per Capita"
      description: "GDP per capita for China"
      category: "cn_growth" 
      frequency: "annual"
      priority: "medium"

  # COLLECTION CONFIGURATION
  collection:
    frequency: "daily"        # How often to check for updates
    history: "max"           # Collect all available history
    format: "parquet"        # Storage format
    chunk_size: 1000         # Records per chunk for large datasets
    timeout: 60              # API timeout in seconds
    retry_attempts: 3        # Number of retry attempts
    
  # DATA QUALITY SETTINGS
  quality:
    min_records: 10          # Minimum records required per indicator
    max_null_pct: 5          # Maximum null percentage allowed
    freshness_days: 90       # Maximum age for data freshness warnings
    outlier_detection: true  # Enable outlier detection
    
  # METADATA CONFIGURATION  
  metadata:
    description: "Federal Reserve Economic Data collection for Australian, US, and global economic indicators"
    source: "https://fred.stlouisfed.org/"
    update_frequency: "Real-time to monthly depending on indicator"
    api_docs: "https://fred.stlouisfed.org/docs/api/"
    data_coverage: "Comprehensive macroeconomic indicators"
    
  # CATEGORIZATION
  categories:
    inflation: "Price levels and inflation measures"
    labour: "Employment and unemployment statistics"
    monetary: "Interest rates and monetary policy"
    growth: "Economic growth and production measures"
    trade: "International trade and external sector"
    us_inflation: "US inflation and price measures"
    us_monetary: "US Federal Reserve policy"
    us_labour: "US employment statistics"
    us_growth: "US economic growth indicators"
    cn_inflation: "Chinese inflation and price measures"
    cn_monetary: "Chinese monetary policy indicators"
    cn_growth: "Chinese economic growth indicators"
    fx: "Foreign exchange rates"
    
  # STATUS
  status: "enhanced"
  last_updated: "2025-08-02"
  total_indicators: 19
  coverage: "Australian (10) + US (4) + Chinese (4) + Global (1)"
  fixes_applied: "Replaced 5 invalid indicator codes with verified working codes"
  enhancements: "Added 4 Chinese economic indicators for trading partner analysis" 