# abs_requirements.yaml  
# Australian Bureau of Statistics Data Collection Configuration
# WEB SCRAPING approach for ABS Key Economic Indicators

abs:
  # DATA SOURCE CONFIGURATION
  source:
    type: "web_scraping"
    url: "https://www.abs.gov.au/statistics/economy/key-indicators"
    method: "html_table_parsing"
    status: "active"
    
  # COLLECTED INDICATOR CATEGORIES (36 total indicators)
  categories:
    - name: "National accounts"
      count: 1
      indicators: ["GDP Chain volume measures"]
      description: "GDP and national accounting measures"
      
    - name: "International accounts" 
      count: 8
      indicators: ["Balance on goods", "Total goods credits", "Total goods debits", "Balance on current account", "Net International Investment Position", "Net foreign debt", "Goods and services credits", "Goods and services debits"]
      description: "Trade balances, goods credits/debits, current account"
      
    - name: "Consumption and investment"
      count: 3
      indicators: ["Retail turnover", "Actual new capital expenditure", "Inventories held by private businesses"]
      description: "Retail turnover, capital expenditure, business inventories"
      
    - name: "Production"
      count: 6
      indicators: ["Income from sales by manufacturers", "Dwelling unit approvals", "Building approvals", "Total dwelling units commenced", "Building work done", "Engineering construction work done"]
      description: "Manufacturing, building approvals, construction activity"
      
    - name: "Prices"
      count: 3  
      indicators: ["Consumer price index", "Producer price indexes", "Import/Export price indexes", "Wage price index"]
      description: "CPI, wage price index, import/export price indexes"
      
    - name: "Labour force and demography"
      count: 7
      indicators: ["Employed persons", "Participation rate", "Unemployment rate", "Employment to population ratio", "Job vacancies", "Estimated resident population", "Short-term overseas visitor arrivals"]
      description: "Employment, unemployment, participation rates, population"
      
    - name: "Incomes"
      count: 2
      indicators: ["Company gross operating profits", "Average weekly ordinary time earnings"]
      description: "Company profits, average weekly earnings"
      
    - name: "Lending indicators"
      count: 6
      indicators: ["New dwelling loan commitments", "Owner occupier commitments", "Investor commitments", "Personal loan commitments", "Business construction commitments", "Business property commitments"]
      description: "Loan commitments for housing and business"

  # COLLECTION CONFIGURATION
  collection:
    frequency: "daily"        # Check for updates daily
    method: "web_scraping"    # Scrape HTML tables
    data_validation: true     # Validate data quality
    save_historical: true     # Keep historical versions
    format: "parquet"         # Storage format
    
  # DATA QUALITY SETTINGS
  quality:
    min_indicators: 30        # Minimum indicators required
    max_null_pct: 20         # Maximum null percentage allowed
    validation_schema: "abs_economic.json"
    
  # METADATA
  metadata:
    description: "Australian Bureau of Statistics Key Economic Indicators"
    source: "https://www.abs.gov.au/statistics/economy/key-indicators"
    collection_method: "Web scraping of official ABS indicator tables"
    update_frequency: "Varies by indicator (monthly/quarterly)"
    data_coverage: "Current economic indicators with latest periods"
    
  # STATUS AND METRICS
  status: "active"
  last_successful_collection: "2025-07-20"
  total_indicators: 36
  success_rate: "100%" 