# cron_schedule.yaml
# Map each ingestion job to a cron schedule

ohlcv_daily: '0 2 * * *'         # 2:00 AM UTC daily
ohlcv_hourly: '0 * * * *'        # Top of every hour
macro_weekly: '0 3 * * 1'        # 3:00 AM UTC every Monday
fundamentals_quarterly: '0 4 1 */3 *' # 4:00 AM UTC, first day of each quarter
